export type School = {
  id: string;
  name: string;
  type: string;
  system: string;
  country: string;
  city: string;
  commune: string;
  address: string;
  gpsLat: number | null;
  gpsLng: number | null;
  phone: string;
  officialEmail: string;
  directorName: string;
  directorPhone: string;
  website: string;
  logoUrl: string;
  logoCldPubId: string;
  studentCount: number | null;
  teacherCount: number | null;
  series: string[];
  legalName?: string;
  registrationNumber?: string;
  accreditationRef?: string;
  academicYearLabel?: string;
  languagesOffered?: string[];
  openingHours?: string;
  socialLinks?: string;
  billingContactName?: string;
  billingEmail?: string;
  billingPhone?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  internalNotes?: string;
  createdAt: string;
  updatedAt: string;
};
